vcf_dir: "38_vcf"
variant_table_path: "example_inputs/regions.tsv"
output_dir: "dev_output"
clinvar: "example_inputs/fake_GRCh38_clinvar_21.tsv"
omim: "example_inputs/genemap2.txt"
covariates: "example_inputs/example_fake_covariates2.tsv"
